# Generated by Django 5.2.6 on 2025-09-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAcademia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100)),
                ('cod_carrera', models.CharField(max_length=20)),
                ('duracion', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
    ]
