# Generated by Django 5.2.6 on 2025-09-28 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAcademia', '0002_carrera_alter_faculty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='Faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='appAcademia.faculty'),
        ),
    ]
