# Generated by Django 5.2.6 on 2025-09-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAcademia', '0005_estudiante_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100)),
                ('cod_materia', models.CharField(max_length=20)),
                ('nivel', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Esta Activo la Materia?')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
    ]
