# Generated by Django 5.2.6 on 2025-09-29 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAcademia', '0006_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='appAcademia.carrera'),
        ),
    ]
