# Generated by Django 5.2.6 on 2025-09-29 04:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAcademia', '0007_materia_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programar_Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Esta Activo la Programacion?')),
                ('fecha_programacion', models.DateField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programar', to='appAcademia.estudiante')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programar', to='appAcademia.materia')),
            ],
            options={
                'verbose_name': 'Programar Materia',
                'verbose_name_plural': 'Programar Materias',
                'unique_together': {('student', 'subject', 'fecha_programacion')},
            },
        ),
    ]
