# Generated by Django 5.2.6 on 2025-09-29 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAcademia', '0008_programar_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programar_materia',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programar_student', to='appAcademia.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='programar_materia',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programar_subject', to='appAcademia.materia', verbose_name='Materia'),
        ),
    ]
